core/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Settings for Manufacturing Cloud Connector for Sales</description>
    <label>Settings</label>
</CustomObject>

core/main/default/objects/Settings__c/fields/CpqEnabled__c.field-meta.xml
<CustomField>
    <fullName>CpqEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Check this box if you are using CPQ. If this is enabled, you must set the Quote Line Account and Sales Agreement Quote Fields in settings.</description>
    <inlineHelpText
  >Check this box if you are using CPQ. If this is enabled, you must set the Quote Line Account and Sales Agreement Quote Fields in settings.</inlineHelpText>
    <label>Enable CPQ</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/Settings__c/fields/MatchQliAccountToSaAccount__c.field-meta.xml
<CustomField>
    <fullName>MatchQliAccountToSaAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Only add Sales Agreement Products to Sales Agreements when the Quote Line&apos;s Account ID matches the Sales Agreement&apos;s Account ID (AccountId__c).</description>
    <inlineHelpText
  >Only add Sales Agreement Products to Sales Agreements when the Quote Line&apos;s Account ID matches the Sales Agreement&apos;s Account ID.</inlineHelpText>
    <label>Match QLI Account to SA Account</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/Settings__c/fields/QliToSapFieldMappingPlugin__c.field-meta.xml
<CustomField>
    <fullName>QliToSapFieldMappingPlugin__c</fullName>
    <description
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</description>
    <inlineHelpText
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</inlineHelpText>
    <label>QLI to SAP Field Mapping Plugin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/Settings__c/fields/QuoteLineAccountField__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineAccountField__c</fullName>
    <defaultValue>&quot;AccountId__c&quot;</defaultValue>
    <description
  >The API name of the field on either the Quote Line (CPQ) or Quote Line Item (Standard) objects that references the Account. Used with the Match QLI Account to SA Account setting to convert quote lines to Sales Agreements with a matching Account. Default values is AccountId__c.</description>
    <inlineHelpText
  >The API name of the field on either the Quote Line (CPQ) or Quote Line Item (Standard) objects that references the Account. Used with the Match QLI Account to SA Account setting to convert quote lines to Sales Agreements with a matching Account. Default values is AccountId__c.</inlineHelpText>
    <label>Quote Line Account Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/Settings__c/fields/SalesAgreementQuoteField__c.field-meta.xml
<CustomField>
    <fullName>SalesAgreementQuoteField__c</fullName>
    <defaultValue>&quot;Quote__c&quot;</defaultValue>
    <description
  >The API Name of the field on the Sales Agreement that references the Quote used to create this Sales Agreement. Must be a reference to a Standard or CPQ Quote. Default field is Quote__c.</description>
    <inlineHelpText
  >The API Name of the field on the Sales Agreement that references the Quote used to create this Sales Agreement. Must be a reference to a Standard or CPQ Quote. Default field is Quote__c.</inlineHelpText>
    <label>Sales Agreement Quote Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/classes/SettingsUtilities.cls
@namespaceAccessible
public with sharing class SettingsUtilities {
    public static Settings__c packageSettings {
        get {
            if (packageSettings == null) {
                packageSettings = Settings__c.getInstance();
            }
            return packageSettings;
        }
        private set;
    }

    public static Boolean isCpqEnabled() {
        return packageSettings.CpqEnabled__c;
    }

    public static String getQliToSapFieldMappingPlugin() {
        return String.isBlank(packageSettings.QliToSapFieldMappingPlugin__c)
            ? 'QuoteLineToSalesAgreementProductMapping'
            : packageSettings.QliToSapFieldMappingPlugin__c;
    }

    public static String getQuoteLineAccountField() {
        return String.isBlank(packageSettings.QuoteLineAccountField__c)
            ? 'AccountId__c'
            : packageSettings.QuoteLineAccountField__c;
    }

    public static String getSalesAgreementQuoteField() {
        return String.isBlank(packageSettings.SalesAgreementQuoteField__c)
            ? 'Quote__c'
            : packageSettings.SalesAgreementQuoteField__c;
    }

    public static Boolean isMatchQliAccountToSaAccount() {
        return packageSettings.MatchQliAccountToSaAccount__c;
    }
}