core/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Settings for Manufacturing Cloud Connector for Sales</description>
    <label>Settings</label>
</CustomObject>

core/main/default/objects/Settings__c/fields/QliToSapFieldMappingPlugin__c.field-meta.xml
<CustomField>
    <fullName>QliToSapFieldMappingPlugin__c</fullName>
    <description
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</description>
    <inlineHelpText
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</inlineHelpText>
    <label>QLI to SAP Field Mapping Plugin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/classes/MappingUtilities_Test.cls
@isTest
private class MappingUtilities_Test {
    @isTest
    static void qliToSapMapping() {
        System.runAs(TestUtilities.testUser) {
            Test.startTest();
            System.assert(!MappingUtilities.qliToSapMapping.sourceToTargetMapping().isEmpty());
            System.assert(!MappingUtilities.qliToSapMapping.fieldsToSumOnMerge().isEmpty());
            System.assert(
                !MappingUtilities.qliToSapMapping.fieldsToWeightedAverageOnMerge().isEmpty()
            );
            Test.stopTest();
        }
    }

    @isTest
    static void invalidQliToSapMapping() {
        System.runAs(TestUtilities.testUser) {
            insert new Settings__c(QliToSapFieldMappingPlugin__c = 'qwerty');
            Test.startTest();
            try {
                FieldMappingConfiguration mapping = MappingUtilities.qliToSapMapping;
                System.assert(false);
            } catch (Exception e) {
                System.assert(e.getMessage().contains('qwerty'));
            }
            Test.stopTest();
        }
    }
}