core/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Settings for Manufacturing Cloud Connector for Sales</description>
    <label>Settings</label>
</CustomObject>

core/main/default/objects/Settings__c/fields/QliToSapFieldMappingPlugin__c.field-meta.xml
<CustomField>
    <fullName>QliToSapFieldMappingPlugin__c</fullName>
    <description
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</description>
    <inlineHelpText
  >Name of Apex Class that contains field mappings from quote lines to sales agreement products. Class must implement the FieldMappingConfiguration interface.</inlineHelpText>
    <label>QLI to SAP Field Mapping Plugin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MappingUtilities.cls
public with sharing class MappingUtilities {
    public static FieldMappingConfiguration qliToSapMapping {
        get {
            if (qliToSapMapping == null) {
                Settings__c packageSettings = Settings__c.getInstance();
                String className = packageSettings.QliToSapFieldMappingPlugin__c == null
                    ? 'QuoteLineToSalesAgreementProductMapping'
                    : packageSettings.QliToSapFieldMappingPlugin__c;
                qliToSapMapping = (FieldMappingConfiguration) Type.forName(className).newInstance();
            }
            return qliToSapMapping;
        }
        private set;
    }
}