core/main/default/objects/QliToSapFieldMapping__mdt/QliToSapFieldMapping__mdt.object-meta.xml
<CustomObject>
    <description
  >Set declarative field mappings from Quote Lines to Sales Agreement Products. Not used if Apex Mapping Plugin is noted in settings.</description>
    <label>QLI to SAP Field Mapping</label>
    <pluralLabel>QLI to SAP Field Mappings</pluralLabel>
</CustomObject>

core/main/default/objects/QliToSapFieldMapping__mdt/fields/QliField__c.field-meta.xml
<CustomField>
    <fullName>QliField__c</fullName>
    <description>Source quote line field.</description>
    <inlineHelpText
  >Source quote line field. Will be mapped to the Sales Agreement Product.</inlineHelpText>
    <label>Quote Line Field (source)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/QliToSapFieldMapping__mdt/fields/SapField__c.field-meta.xml
<CustomField>
    <fullName>SapField__c</fullName>
    <description>Target Sales Agreement Product field.</description>
    <inlineHelpText
  >Target Sales Agreement Product field. Will be mapped from the Quote Line.</inlineHelpText>
    <label>Sales Agreement Product Field (target)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/QliToSapFieldMapping__mdt/fields/SumOnMerge__c.field-meta.xml
<CustomField>
    <fullName>SumOnMerge__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >When the Sales Agreement Product is merged, should the value be summed (must be a number data type)?</description>
    <inlineHelpText
  >When the Sales Agreement Product is merged, should the value be summed (must be a number data type)?</inlineHelpText>
    <label>Sum Field on Merge</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/QliToSapFieldMapping__mdt/fields/WeightedAverageOnMerge__c.field-meta.xml
<CustomField>
    <fullName>WeightedAverageOnMerge__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >When the Sales Agreement Product is merged, should the weighted average be calculated (must be a number data type)? The quantity is used to calculate the weighted average.</description>
    <inlineHelpText
  >When the Sales Agreement Product is merged, should the weighted average be calculated (must be a number data type)? The quantity is used to calculate the weighted average.</inlineHelpText>
    <label>Weighted Average of Field on Merge</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/classes/QuoteLineToSalesAgreementProductMapping.cls
// Default mapping plugin for Quote Line to Sales Agreement Product
public with sharing class QuoteLineToSalesAgreementProductMapping implements FieldMappingConfiguration {
    private static Map<String, String> cachedSourceToTargetMapping;
    private static Set<String> cachedFieldsToSumOnMerge;
    private static Set<String> cachedFieldsToWeightedAverageOnMerge;

    public static Map<String, String> sourceToTargetMapping() {
        if (cachedSourceToTargetMapping == null) {
            getCustomMetadataValues();
        }
        return cachedSourceToTargetMapping;
    }
    public static Set<String> fieldsToSumOnMerge() {
        if (cachedFieldsToSumOnMerge == null) {
            getCustomMetadataValues();
        }
        return cachedFieldsToSumOnMerge;
    }
    public static Set<String> fieldsToWeightedAverageOnMerge() {
        if (cachedFieldsToWeightedAverageOnMerge == null) {
            getCustomMetadataValues();
        }
        return cachedFieldsToWeightedAverageOnMerge;
    }

    private static void getCustomMetadataValues() {
        cachedSourceToTargetMapping = new Map<String, String>();
        cachedFieldsToSumOnMerge = new Set<String>();
        cachedFieldsToWeightedAverageOnMerge = new Set<String>();
        for (QliToSapFieldMapping__mdt mapping : QliToSapFieldMapping__mdt.getAll().values()) {
            cachedSourceToTargetMapping.put(mapping.QliField__c, mapping.SapField__c);
            if (mapping.SumOnMerge__c) {
                cachedFieldsToSumOnMerge.add(mapping.SapField__c);
            }
            if (mapping.WeightedAverageOnMerge__c) {
                cachedFieldsToWeightedAverageOnMerge.add(mapping.SapField__c);
            }
        }
    }
}