core/main/default/objects/QuoteLineItem/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Used to tie a quote line to a specific Account. Use this if you enable the Match QLI Account to SA Account setting to map which sales agreements this quote line will be added to.</description>
    <inlineHelpText
  >Used to tie a quote line to a specific Account. Use this if you enable the Match QLI Account to SA Account setting to map which sales agreements this quote line will be added to.</inlineHelpText>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

core/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description
  >Settings for Manufacturing Cloud Connector for Sales</description>
    <label>Settings</label>
</CustomObject>

core/main/default/objects/Settings__c/fields/MatchQliAccountToSaAccount__c.field-meta.xml
<CustomField>
    <fullName>MatchQliAccountToSaAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Only add Sales Agreement Products to Sales Agreements when the Quote Line&apos;s Account ID matches the Sales Agreement&apos;s Account ID (AccountId__c).</description>
    <inlineHelpText
  >Only add Sales Agreement Products to Sales Agreements when the Quote Line&apos;s Account ID matches the Sales Agreement&apos;s Account ID.</inlineHelpText>
    <label>Match QLI Account to SA Account</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/classes/QuoteToSalesAgreementService_Test.cls
@isTest
private class QuoteToSalesAgreementService_Test {
    @isTest
    static void createSalesAgreementProducts() {
        System.runAs(TestUtilities.testUser) {
            SalesAgreement testAgreement = TestUtilities.testSalesAgreement;
            QuoteLineItem qli = TestUtilities.testQuoteLine;
            QuoteLineItem qli2 = qli.clone(false, true, false, false);
            insert qli2;
            Test.startTest();
            QuoteToSalesAgreementService.createSalesAgreementProducts(
                new List<SalesAgreement>{ testAgreement }
            );
            Test.stopTest();
            List<SalesAgreementProduct> saps = [
                SELECT InitialPlannedQuantity, SalesPrice
                FROM SalesAgreementProduct
                WHERE SalesAgreementId = :testAgreement.Id
            ];
            System.assertEquals(1, saps.size());

            System.assertEquals(2, saps[0].InitialPlannedQuantity);
            System.assertEquals(1000, saps[0].SalesPrice);
        }
    }

    @isTest
    static void createSalesAgreementProductsMatchQuotes() {
        System.runAs(TestUtilities.testUser) {
            insert new Settings__c(MatchQliAccountToSaAccount__c = true);
            Account testAccount2 = TestUtilities.testAccount.clone(false, true, false, false);
            insert testAccount2;
            SalesAgreement testAgreement = TestUtilities.testSalesAgreement;
            SalesAgreement testAgreement2 = testAgreement.clone(false, true, false, false);
            testAgreement2.AccountId = testAccount2.Id;
            insert testAgreement2;
            QuoteLineItem qli = TestUtilities.testQuoteLine;
            QuoteLineItem qli2 = qli.clone(false, true, false, false);
            qli2.AccountId__c = testAccount2.Id;
            insert qli2;
            Test.startTest();
            QuoteToSalesAgreementService.createSalesAgreementProducts(
                new List<SalesAgreement>{ testAgreement, testAgreement2 }
            );
            Test.stopTest();
            List<SalesAgreementProduct> saps = [
                SELECT InitialPlannedQuantity, SalesPrice
                FROM SalesAgreementProduct
                WHERE SalesAgreementId = :testAgreement.Id
            ];
            System.assertEquals(1, saps.size());

            System.assertEquals(1, saps[0].InitialPlannedQuantity);
            System.assertEquals(1000, saps[0].SalesPrice);

            List<SalesAgreementProduct> saps2 = [
                SELECT InitialPlannedQuantity, SalesPrice
                FROM SalesAgreementProduct
                WHERE SalesAgreementId = :testAgreement2.Id
            ];
            System.assertEquals(1, saps2.size());

            System.assertEquals(1, saps2[0].InitialPlannedQuantity);
            System.assertEquals(1000, saps2[0].SalesPrice);
        }
    }
}